# Generated by Django 3.0.5 on 2020-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityPeriod',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
