# Generated by Django 3.0.5 on 2020-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailApp', '0002_auto_20200506_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=64)),
                ('tz', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
