# Generated by Django 3.0.5 on 2020-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailApp', '0005_auto_20200506_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity_period',
        ),
        migrations.AddField(
            model_name='members',
            name='endtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='members',
            name='starttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
