# Generated by Django 3.0.5 on 2020-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailApp', '0006_auto_20200506_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now=True)),
                ('endtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='members',
            name='starttime',
        ),
    ]
